name: Build and publish Rust SDK
on:
  workflow_call:
    inputs:
      is-release:
        default: false
        type: boolean
        description: Whether this is a release package ready to be published or not.

  workflow_dispatch:
    inputs:
      is-release:
        default: false
        type: boolean
        description: Whether this is a release package ready to be published or not.

jobs:
  build-publish-rust-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag version
        run: |
          echo "SDK_VERSION=$(git describe --tags --abbrev=0 | cut -c2-)" >> $GITHUB_ENV

      - name: Create nightly version, if applicable.
        if: ${{ inputs.is-release == false }}
        run: |
          echo "SDK_VERSION=${{ env.SDK_VERSION }}+git$(date +'%Y%m%d').$(git rev-parse --short HEAD)-${{ github.run_attempt }}" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-edit
        run: |
          cargo install cargo-edit

      - name: Set the package version.
        run: |
          cargo set-version ${{ env.SDK_VERSION }}

      - name: Build
        run: |
          cargo build --release --verbose      

      - name: Share artifacts.
        uses: actions/upload-artifact@v4
        with:
          name: "realitydefender-sdk-rust-${{ env.SDK_VERSION }}"
          path: |
            target/**/librealitydefender*.*
          compression-level: 0
          retention-days: 14
          if-no-files-found: error

      - name: Publish
        if: ${{ inputs.is-release == true }}
        run: |
          cargo publish --allow-dirty --no-verify --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
     
