name: Format, check, and test Rust SDK

on:
  workflow_call:

jobs:
  format-check-test-rust-sdk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin/cargo-tarpaulin
            rust/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: |
          cargo fmt --all -- --check

      - name: Lint with clippy
        run: |
          cargo clippy --no-deps -- -D warnings

      - name: Install cargo-tarpaulin
        run: |
          cargo install cargo-tarpaulin

      - name: Generate coverage report
        run: |
          cargo tarpaulin --all-features --out Xml --output-dir ./

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cobertura.xml
          flags: rust
          name: rust-sdk-codecov
          fail_ci_if_error: true
