name: Build Rust SDK

on:
  workflow_run:
    workflows: ["Test Rust SDK"]
    types:
      - completed
    branches: [main]

jobs:
  build-crate:
    # Only run if the test workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release --verbose
      
      - name: Create package archive
        run: |
          cargo package --allow-dirty
          
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: realitydefender-package
          path: target/package/
          retention-days: 30
